### PR TITLE
Added support for Docker

### PR DESCRIPTION
**Pull request by MarcOrfilaCarreras**
Hi @aks579,

I would like to contribute in order to enhance the project's deployment and development process.

I've made the following changes to your project:

- Added Dockerfile: This file includes the necessary instructions to build a Docker image for the application. It specifies the base image, required dependencies, and sets up the environment.

- Added docker-compose.yml: This file defines the services, networks, and configurations needed to orchestrate the containers for the application. It simplifies the process of setting up the development environment.

- Modified README.md: Added the instructions to use Docker.

These changes allow your project to be run smoothly within a Docker container, making it more portable across different environments and simplifying the setup process.

I've tested these changes on my own system. Please review them and test in your environment to make sure they work well for you too.

### CODE REVIEW

**Comment by aks579** [comment]
Hi @MarcOrfilaCarreras , 

Thank you for the contribution. Making this a docker container is a great way to simplify the setup process.
I have also tested this on my linux setup and is working fine.
There's just one query - the files created on host machine have root as user and group. While I am able to modify the files from the application, I am unable to do so from the local machine filesystem itself. Is there a way to circumvent this?

**Comment by MarcOrfilaCarreras** [comment]
Hi @aks579,
Now, the files are being created with the correct user! 🚀 This only happens if the same user creates the 'data' folder before running the container.

To make this happen seamlessly, I have added a couple of parameters in the docker-compose.yml file to set the UID and GID. So, no more mismatched files causing headaches! 😅

Let me know if you have any thoughts or spot anything else that needs fixing.

**Comment by aks579** [comment]
Hi @MarcOrfilaCarreras,

The new code is giving below error - 
quilly  | [2023-10-24 10:18:08 +0000] [1] [INFO] Starting gunicorn 21.2.0
quilly  | [2023-10-24 10:18:08 +0000] [1] [ERROR] Retrying in 1 second.
quilly  | [2023-10-24 10:18:09 +0000] [1] [ERROR] Retrying in 1 second.
quilly  | [2023-10-24 10:18:10 +0000] [1] [ERROR] Retrying in 1 second.
quilly  | [2023-10-24 10:18:11 +0000] [1] [ERROR] Retrying in 1 second.
quilly  | [2023-10-24 10:18:12 +0000] [1] [ERROR] Retrying in 1 second.
quilly  | [2023-10-24 10:18:13 +0000] [1] [ERROR] Can't connect to ('0.0.0.0', 80)

Port 80 requires superuser privileges. Please change the port 80 to 8000.
It is working after changing the port.

**Comment by MarcOrfilaCarreras** [comment]
Hi @aks579,

I have just updated the code.

**Pull request merged**
